/** Versioned source shared by public pages, acceptance and the AI help tool. */
export const LEGAL_VERSION = '2026-09-08';
export const LEGAL_CONTACT = 'reaganfraizer13@gmail.com';
export type LegalKind = 'terms' | 'privacy';
export type LegalSection = { id: string; title: string; paragraphs: string[] };
export type LegalDocument = { title: string; lead: string; sections: LegalSection[] };
export const legalDocuments: Record<'sw' | 'en', Record<LegalKind, LegalDocument>> = {
  en: {
    terms: { title: 'Terms of service', lead: 'Clear responsibilities. Your business stays in your control.', sections: [
      { id: 'agreement', title: '01 / Your agreement with Risip', paragraphs: ['These terms govern your use of Risip, the business management service at risip.online. By actively accepting them, you agree to these terms. If you act for a business, you confirm that you have authority to use the service on its behalf. You must be at least 18 and legally able to enter this agreement.', 'Risip’s published contact is reaganfraizer13@gmail.com, Mbezi Shule, Dar es Salaam, Tanzania. The Privacy Notice explains personal-data processing separately; accepting these terms is not blanket permission for advertising or unrelated processing.'] },
      { id: 'service', title: '02 / What the service does', paragraphs: ['The Risip app is the main place to chat about sales, purchases, stock, expenses, debts and reports. WhatsApp supports account access, verification, invitations and reminders. Features and permissions vary by role, business configuration and subscription.', 'Risip helps organize records. It is not a bank, auditor, tax authority, lender or regulated investment adviser. A recorded payment is not independent proof that money settled. Verify bank, mobile-money and supplier records where needed.'] },
      { id: 'ai', title: '03 / AI and financial decisions', paragraphs: ['AI may misunderstand language, quantities, product names or context. Read each proposed record, price, unit, date, party and total before confirming. A draft is not a confirmed transaction. Do not rely on a conversational answer alone for a tax filing, payment, procurement commitment or other material decision.', 'You retain control of approvals and corrections available to your role. Do not instruct the assistant to bypass access rules or confirmation. Report incorrect answers; Risip may refuse a request when required information or reliable evidence is missing.'] },
      { id: 'account', title: '04 / Accounts and team access', paragraphs: ['Provide accurate account and business information. Keep login links, codes and devices secure; do not forward private credentials. Tell Risip promptly about suspected unauthorized access. Business owners must assign appropriate roles and remove access when staff leave.', 'Only upload and process information you are entitled to use, including customer, supplier and employee information. Do not use another person’s account or claim authority you do not have.'] },
      { id: 'acceptable-use', title: '05 / Acceptable use', paragraphs: ['Do not use Risip for fraud, unlawful transactions, impersonation, harassment, malicious software, unauthorized access, deliberate overload or falsification of records. Do not submit passwords, payment-card security codes or unrelated sensitive personal information into chat.', 'Risip may restrict access where reasonably necessary to address misuse, security threats, legal obligations or unpaid subscriptions. Where practical, we will explain the reason and how to contact us about a mistake.'] },
      { id: 'billing', title: '06 / Plans, payments and cancellation', paragraphs: ['The plan, price, billing period and any applicable taxes shown before purchase govern that purchase. Review the payment request before authorizing it. Do not treat an AI estimate or an old conversation as the current price. Payment providers may apply their own terms and charges.', 'You may request cancellation, a plan change or a billing correction through support or the available account controls. Refund requests are assessed against the purchase circumstances and applicable law. These terms do not remove mandatory refund or consumer rights. Cancellation does not reverse an already confirmed business transaction.'] },
      { id: 'content', title: '07 / Your records and our software', paragraphs: ['You retain your rights in your business records. You give Risip the permission needed to host, process, display and transmit them to operate and secure the service and provide features you request. This does not transfer ownership of your records.', 'Risip’s software, branding and service design remain protected by their respective intellectual-property rights. Keep copies of records you need to retain outside the service, using available exports or support where appropriate.'] },
      { id: 'availability', title: '08 / Availability and third parties', paragraphs: ['We work to provide a reliable service, but cannot promise uninterrupted access or error-free AI. Maintenance, connectivity, hosting, messaging and payment-provider interruptions can affect availability. Third-party links and services may have their own policies.', 'Review important records and keep appropriate backups for your business. Report incidents using the published contact. We do not promise recovery of every deleted or unavailable item.'] },
      { id: 'responsibility', title: '09 / Responsibility and disputes', paragraphs: ['Each party is responsible for its obligations under this agreement and applicable law. Risip does not guarantee business profits, tax outcomes, supplier performance or the accuracy of information entered by users. Nothing in these terms excludes rights or liability that applicable law does not allow to be excluded.', 'Contact support first with the issue and relevant dates so we can seek a practical resolution. If it is not resolved, either party may use the competent authorities or courts available under applicable law. No clause requires you to surrender mandatory legal protections.'] },
      { id: 'changes', title: '10 / Changes and leaving', paragraphs: ['We may update these terms as the service changes. The published version identifies the applicable text. Material changes will be brought to your attention and may require renewed acceptance. Continued access is not a substitute for an explicit acceptance screen where one is required.', 'You may stop using the service and request account closure. Business records, team access and legally required retention may need separate handling, as explained in the Privacy Notice. Contact reaganfraizer13@gmail.com with questions or requests.'] },
    ] },
    privacy: { title: 'Privacy notice', lead: 'Understand what you share, why it is used, and the choices you have.', sections: [
      { id: 'scope', title: '01 / Who this notice covers', paragraphs: ['This notice explains how Risip handles personal information in its app, website and connected messaging features. For account, security and subscription information, Risip determines the purposes of processing. For customer, supplier and staff records entered by a business, that business generally determines why the records are used and must have authority to process them.', 'For privacy questions, contact reaganfraizer13@gmail.com. The published service location is Mbezi Shule, Dar es Salaam, Tanzania. A business administrator’s access does not make all of its staff records public.'] },
      { id: 'data', title: '02 / Information processed', paragraphs: ['Information can include your name, phone number, business name and location, role and membership; chat messages and attachments; receipts and product, stock, sales, expense, debt and payment records; subscription and billing metadata; support requests; and the policy version and time you accept.', 'Technical records can include request identifiers, device/browser information, IP addresses used for abuse controls, session information and diagnostic events. Login credentials are access secrets; avoid including them in ordinary chat or support screenshots.'] },
      { id: 'purpose', title: '03 / Why information is used', paragraphs: ['We process information to provide the service you request: authenticate accounts, manage business access, interpret messages and receipts, prepare and display records, deliver reminders and invitations, handle subscriptions and support, and maintain security and reliability.', 'Processing must have an applicable legal basis, such as providing a requested service or contract, a legal obligation, a permitted legitimate interest, or consent where required. We do not treat acceptance of service terms as consent to every possible use. Where optional processing relies on consent, you may withdraw it without making earlier lawful processing unlawful.'] },
      { id: 'ai-data', title: '04 / AI processing and human control', paragraphs: ['Relevant messages, receipt content, bounded conversation context and business information may be sent to AI providers to interpret a request and prepare a response. Do not include unrelated sensitive information. AI responses can be wrong; a human should check consequential decisions and proposed records.', 'Risip uses service providers for AI processing. Provider settings, contracts and applicable policies govern their handling of submitted data. This notice does not promise that no external provider ever stores data, nor that every AI output is correct.'] },
      { id: 'sharing', title: '05 / Service providers and sharing', paragraphs: ['The service uses infrastructure and vendors including Supabase for backend services, Anthropic for AI, Vercel for web hosting, Meta/WhatsApp for messaging, and configured email or payment providers when those features are used. Information shared depends on the feature; not every provider receives every record.', 'Authorized members of your business can see information according to their permissions. Information may also be disclosed where required by law, to protect lawful rights or security, or as necessary in a lawful business transfer with appropriate protections. Do not assume a link to a third-party service is covered only by this notice.'] },
      { id: 'transfers', title: '06 / Where processing happens', paragraphs: ['Providers may process or store information outside Tanzania. The destination depends on the configured infrastructure and provider. International transfers must follow applicable data-protection requirements, including safeguards and regulatory approvals where required. Acceptance of this notice alone does not replace those obligations.', 'You may contact us to ask about relevant providers, processing locations and safeguards. We do not claim that every provider operates only in Tanzania or that regulatory approval has been granted merely because this notice is published.'] },
      { id: 'retention', title: '07 / Retention and deletion', paragraphs: ['Business records are retained to support the active service, accounting history, security, legal obligations and legitimate dispute handling. Different records have different lifecycles: a short-lived login link, an operational diagnostic and a confirmed ledger entry are not retained for the same reason.', 'Account closure may not erase records that belong to another business or must be retained under law. Deletion from active systems may take additional time to pass through backups. Ask support about access, export or deletion of particular records; we will explain any applicable retention restriction rather than promise immediate universal deletion.'] },
      { id: 'security', title: '08 / Security and local storage', paragraphs: ['Risip uses authentication, business-scoped permissions and audit controls to help protect records. No system is completely secure. Protect your devices and notify us about suspected unauthorized access.', 'The web app uses browser storage for sessions and practical preferences or drafts, such as language, chat appearance and pending sends. Clearing browser storage or sharing a device affects these features. Optional tracking or marketing technologies, if introduced, require appropriate notice and choices.'] },
      { id: 'rights', title: '09 / Your rights and complaints', paragraphs: ['Subject to applicable law, you may request access, correction, erasure, restriction or objection to processing, and information about how your data is handled. Where applicable, you may withdraw consent. We may need to verify your identity and authority before disclosing or changing a business record.', 'Contact reaganfraizer13@gmail.com with a clear request. If your concern relates to records controlled by your employer or another business, we may need to involve that business. You may also complain to the competent data-protection authority, including Tanzania’s Personal Data Protection Commission at pdpc.go.tz.'] },
      { id: 'updates', title: '10 / Children and notice updates', paragraphs: ['Risip is intended for adults operating or working in a business, not for children. Do not knowingly create an account for a child or submit unrelated children’s personal information.', 'We may update this notice to reflect service or legal changes. The version and current notice remain accessible. We will provide additional notice or seek consent when required for a material change in processing.'] },
    ] },
  },
  sw: {
    terms: { title: 'Masharti ya matumizi', lead: 'Wajibu ulio wazi. Udhibiti wa biashara unabaki mikononi mwako.', sections: [
      { id:'agreement', title:'01 / Makubaliano yako na Risip', paragraphs:['Masharti haya yanahusu matumizi ya huduma ya Risip kwenye risip.online. Unapoyakubali kwa hatua ya wazi, unakubaliana nayo. Ikiwa unatumia huduma kwa niaba ya biashara, unathibitisha kuwa una mamlaka ya kufanya hivyo. Lazima uwe na miaka 18 au zaidi na uwezo wa kisheria wa kuingia makubaliano.', 'Mawasiliano yaliyochapishwa ya Risip ni reaganfraizer13@gmail.com, Mbezi Shule, Dar es Salaam, Tanzania. Taarifa ya Faragha inaeleza matumizi ya taarifa binafsi kando; kukubali masharti si ruhusa ya jumla ya matangazo au matumizi yasiyohusiana na huduma.'] },
      { id:'service', title:'02 / Huduma inayotolewa', paragraphs:['App ya Risip ndiyo sehemu kuu ya kuzungumza kuhusu mauzo, manunuzi, stock, matumizi, madeni na ripoti. WhatsApp husaidia kuingia, kuhakiki akaunti, mialiko na vikumbusho. Vipengele hutegemea nafasi yako, mipangilio ya biashara na kifurushi.', 'Risip husaidia kupanga rekodi. Si benki, mkaguzi wa hesabu, mamlaka ya kodi, mkopeshaji wala mshauri wa uwekezaji mwenye leseni. Rekodi ya malipo si uthibitisho huru kwamba fedha zimefika. Hakiki taarifa za benki, simu na wasambazaji inapohitajika.'] },
      { id:'ai', title:'03 / AI na maamuzi ya fedha', paragraphs:['AI inaweza kukosea lugha, idadi, majina ya bidhaa au muktadha. Hakiki bei, kipimo, tarehe, mhusika na jumla kabla ya kuthibitisha rekodi. Draft si muamala uliothibitishwa. Usitumie jibu la mazungumzo pekee kuwasilisha kodi, kufanya malipo, kuagiza mzigo au kufanya uamuzi mkubwa.', 'Unaendelea kudhibiti uthibitisho na marekebisho yanayoruhusiwa na nafasi yako. Usiagize AI kukwepa ruhusa au uthibitisho. Ripoti jibu lisilo sahihi; Risip inaweza kukataa ombi ikiwa taarifa muhimu au ushahidi wa kuaminika haupo.'] },
      { id:'account', title:'04 / Akaunti na timu yako', paragraphs:['Toa taarifa sahihi za akaunti na biashara. Linda link za kuingia, kodi na vifaa vyako; usitume siri za kuingia kwa wengine. Tujulishe ukishuku matumizi yasiyoidhinishwa. Mmiliki wa biashara anapaswa kutoa ruhusa zinazofaa na kuondoa ruhusa za wafanyakazi wanaoondoka.', 'Weka taarifa unazoruhusiwa kutumia tu, zikiwemo taarifa za wateja, wasambazaji na wafanyakazi. Usitumie akaunti ya mtu mwingine au kudai mamlaka usiyo nayo.'] },
      { id:'acceptable-use', title:'05 / Matumizi yanayokubalika', paragraphs:['Usitumie Risip kufanya udanganyifu, miamala haramu, kujifanya mtu mwingine, unyanyasaji, kusambaza programu hatari, kuvamia mfumo, kuulemea kimakusudi au kughushi rekodi. Usiweke password, kodi za usalama za kadi au taarifa nyeti zisizohusiana na kazi kwenye chat.', 'Risip inaweza kuzuia huduma inapohitajika kushughulikia matumizi mabaya, tishio la usalama, wajibu wa kisheria au kifurushi kisicholipiwa. Inapowezekana, tutaeleza sababu na namna ya kuwasiliana kuhusu kosa.'] },
      { id:'billing', title:'06 / Vifurushi, malipo na kusitisha', paragraphs:['Kifurushi, bei, kipindi cha malipo na kodi zinazoonyeshwa kabla ya kununua ndizo zinazohusu ununuzi huo. Hakiki ombi la malipo kabla ya kuliruhusu. Makadirio ya AI au mazungumzo ya zamani si bei ya sasa. Mtoa huduma wa malipo anaweza kuwa na masharti na tozo zake.', 'Unaweza kuomba kusitisha kifurushi, kubadilisha plan au kusahihisha bili kupitia msaada au vitufe vilivyopo. Maombi ya kurejeshewa fedha yatapimwa kwa kuzingatia ununuzi na sheria. Masharti haya hayaondoi haki za lazima za mlaji. Kusitisha kifurushi hakufuti muamala wa biashara uliothibitishwa.'] },
      { id:'content', title:'07 / Rekodi zako na programu yetu', paragraphs:['Haki zako kwenye rekodi za biashara zinabaki zako. Unaipa Risip ruhusa inayohitajika kuzihifadhi, kuzichakata, kuzionyesha na kuzifikisha ili kutoa na kulinda huduma uliyoomba. Hii haihamishi umiliki wa rekodi.', 'Programu, chapa na muundo wa Risip zinalindwa na haki husika za ubunifu. Hifadhi nakala za rekodi unazohitaji nje ya huduma, kupitia njia za kupakua zilizopo au msaada inapofaa.'] },
      { id:'availability', title:'08 / Upatikanaji na huduma nyingine', paragraphs:['Tunafanya kazi kutoa huduma inayotegemeka, lakini hatuwezi kuahidi upatikanaji usiokatika au AI isiyokosea. Matengenezo, mtandao, hosting, ujumbe na mtoa huduma wa malipo vinaweza kuathiri upatikanaji. Huduma za wengine zinaweza kuwa na sera zao.', 'Hakiki rekodi muhimu na uwe na nakala zinazofaa kwa biashara yako. Ripoti hitilafu kupitia mawasiliano yaliyochapishwa. Hatuahidi kurejesha kila taarifa iliyofutwa au isiyopatikana.'] },
      { id:'responsibility', title:'09 / Wajibu na migogoro', paragraphs:['Kila upande unawajibika kwa majukumu yake chini ya makubaliano haya na sheria. Risip haihakikishi faida ya biashara, matokeo ya kodi, utendaji wa msambazaji au usahihi wa taarifa zilizoingizwa na mtumiaji. Hakuna kipengele kinachoondoa haki au wajibu ambao sheria hairuhusu kuondolewa.', 'Wasiliana nasi kwanza ukieleza tatizo na tarehe husika ili tutafute suluhisho. Lisipotatuliwa, kila upande unaweza kutumia mamlaka au mahakama yenye uwezo chini ya sheria zinazotumika. Huhitajiki kuachana na ulinzi wa lazima wa kisheria.'] },
      { id:'changes', title:'10 / Mabadiliko na kuondoka', paragraphs:['Masharti yanaweza kubadilishwa huduma inapobadilika. Toleo lililochapishwa linatambulisha maandishi yanayotumika. Mabadiliko makubwa yataletwa kwako na yanaweza kuhitaji ukubali tena. Kuendelea kutumia huduma hakuchukui nafasi ya kukubali wazi pale kunapohitajika.', 'Unaweza kuacha kutumia huduma na kuomba kufunga akaunti. Rekodi za biashara, ruhusa za timu na uhifadhi unaotakiwa kisheria vinaweza kuhitaji kushughulikiwa tofauti kama ilivyoelezwa kwenye Taarifa ya Faragha. Maswali na maombi: reaganfraizer13@gmail.com.'] },
    ] },
    privacy: { title:'Taarifa ya faragha', lead:'Fahamu taarifa unazoshiriki, sababu za matumizi yake na chaguo ulizo nazo.', sections:[
      { id:'scope', title:'01 / Taarifa hii inamhusu nani', paragraphs:['Taarifa hii inaeleza jinsi Risip inavyoshughulikia taarifa binafsi kwenye app, website na huduma za ujumbe zilizounganishwa. Risip huamua sababu za kuchakata taarifa za akaunti, usalama na kifurushi. Kwa rekodi za wateja, wasambazaji na wafanyakazi zinazowekwa na biashara, kwa kawaida biashara hiyo huamua matumizi na inapaswa kuwa na mamlaka ya kuzichakata.', 'Maswali ya faragha: reaganfraizer13@gmail.com. Eneo la huduma lililochapishwa ni Mbezi Shule, Dar es Salaam, Tanzania. Ruhusa ya msimamizi wa biashara haifanyi rekodi za wafanyakazi kuwa za umma.'] },
      { id:'data', title:'02 / Taarifa zinazochakatwa', paragraphs:['Taarifa zinaweza kujumuisha jina, namba ya simu, jina na eneo la biashara, nafasi na uanachama; ujumbe na viambatisho; risiti, bidhaa, stock, mauzo, matumizi, madeni na malipo; taarifa za kifurushi na bili; maombi ya msaada; pamoja na toleo la sera na muda uliokubali.', 'Rekodi za kiufundi zinaweza kujumuisha vitambulisho vya maombi, taarifa za browser/kifaa, IP kwa udhibiti wa matumizi mabaya, session na matukio ya uchunguzi wa mfumo. Link na kodi za kuingia ni siri; usiziweke kwenye chat ya kawaida au picha za msaada.'] },
      { id:'purpose', title:'03 / Kwa nini taarifa hutumika', paragraphs:['Tunachakata taarifa kutoa huduma unayoomba: kuhakiki akaunti, kusimamia ruhusa, kuelewa ujumbe na risiti, kuandaa rekodi, kutoa vikumbusho na mialiko, kushughulikia vifurushi na msaada, na kulinda usalama na utegemevu wa mfumo.', 'Uchakataji unapaswa kuwa na msingi halali, kama kutoa huduma/mkataba ulioombwa, wajibu wa kisheria, maslahi halali yanayoruhusiwa au ridhaa inapohitajika. Kukubali masharti si ridhaa ya kila matumizi. Unaweza kuondoa ridhaa ya matumizi ya hiari bila kufanya uchakataji wa awali uliokuwa halali kuwa haramu.'] },
      { id:'ai-data', title:'04 / AI na udhibiti wa binadamu', paragraphs:['Ujumbe husika, maudhui ya risiti, sehemu yenye mipaka ya historia ya mazungumzo na taarifa za biashara vinaweza kutumwa kwa watoa huduma wa AI ili kuelewa ombi na kuandaa jibu. Epuka taarifa nyeti zisizohusika. Binadamu anapaswa kuhakiki maamuzi muhimu na rekodi zinazopendekezwa.', 'Mipangilio, mikataba na sera husika za mtoa huduma zinaongoza namna anavyoshughulikia taarifa. Hatutoi ahadi kwamba hakuna mtoa huduma wa nje anayehifadhi taarifa, wala kwamba kila jibu la AI ni sahihi.'] },
      { id:'sharing', title:'05 / Watoa huduma na kushirikisha taarifa', paragraphs:['Huduma hutumia Supabase kwa backend, Anthropic kwa AI, Vercel kwa hosting, Meta/WhatsApp kwa ujumbe, na watoa huduma wa email au malipo waliowekwa pale vipengele hivyo vinapotumika. Taarifa zinazoshirikishwa hutegemea kipengele; si kila mtoa huduma hupokea kila rekodi.', 'Wanachama walioidhinishwa wa biashara yako wanaweza kuona taarifa kulingana na ruhusa. Taarifa zinaweza pia kutolewa sheria inapohitaji, kulinda haki au usalama, au katika uhamisho halali wa biashara wenye ulinzi unaofaa. Huduma ya nje inaweza kuwa na sera yake.'] },
      { id:'transfers', title:'06 / Mahali taarifa zinapochakatwa', paragraphs:['Watoa huduma wanaweza kuchakata au kuhifadhi taarifa nje ya Tanzania. Eneo hutegemea miundombinu na mtoa huduma. Uhamisho wa kimataifa unapaswa kufuata matakwa ya ulinzi wa taarifa, zikiwemo kinga na vibali vinapohitajika. Kukubali taarifa hii pekee hakuchukui nafasi ya wajibu huo.', 'Wasiliana nasi kuuliza kuhusu watoa huduma, maeneo na kinga husika. Hatudai kwamba kila mtoa huduma yupo Tanzania tu au kwamba kuchapisha sera hii kunamaanisha vibali vya mamlaka vimetolewa.'] },
      { id:'retention', title:'07 / Kuhifadhi na kufuta', paragraphs:['Rekodi huhifadhiwa kusaidia huduma inayoendelea, historia ya hesabu, usalama, wajibu wa kisheria na kushughulikia migogoro halali. Link ya kuingia ya muda mfupi, kumbukumbu ya hitilafu na rekodi ya fedha iliyothibitishwa zina sababu na vipindi tofauti vya uhifadhi.', 'Kufunga akaunti kunaweza kutofuta rekodi za biashara nyingine au zinazohitajika kisheria. Kufuta kwenye mfumo hai kunaweza kuchukua muda zaidi kuondoa nakala za backup. Omba msaada kwa ufikiaji, nakala au kufuta rekodi maalumu; tutaeleza kizuizi kinachotumika badala ya kuahidi kufuta kila kitu papo hapo.'] },
      { id:'security', title:'08 / Usalama na hifadhi ya browser', paragraphs:['Risip hutumia uthibitisho wa akaunti, ruhusa kwa biashara na kumbukumbu za ukaguzi kusaidia kulinda taarifa. Hakuna mfumo ulio salama kwa asilimia zote. Linda vifaa na utujulishe ukishuku matumizi yasiyoidhinishwa.', 'App hutumia hifadhi ya browser kwa session, lugha, muonekano wa chat, draft na ujumbe unaosubiri kutumwa. Kufuta hifadhi au kutumia kifaa pamoja huathiri vipengele hivyo. Ufuatiliaji au matangazo ya hiari yakiongezwa yatahitaji taarifa na chaguo zinazofaa.'] },
      { id:'rights', title:'09 / Haki zako na malalamiko', paragraphs:['Kwa kuzingatia sheria, unaweza kuomba kuona, kusahihisha, kufuta, kuzuia au kupinga uchakataji wa taarifa, na kupewa maelezo ya matumizi. Unaweza kuondoa ridhaa inapohusika. Tunaweza kuhitaji kuhakiki utambulisho na mamlaka yako kabla ya kutoa au kubadili rekodi.', 'Tuma ombi wazi kwa reaganfraizer13@gmail.com. Rekodi zinazodhibitiwa na mwajiri au biashara nyingine zinaweza kuhitaji biashara hiyo ihusishwe. Unaweza pia kulalamika kwa mamlaka yenye uwezo, ikiwemo Tume ya Ulinzi wa Taarifa Binafsi Tanzania: pdpc.go.tz.'] },
      { id:'updates', title:'10 / Watoto na mabadiliko ya taarifa', paragraphs:['Risip imekusudiwa watu wazima wanaoendesha au kufanya kazi kwenye biashara. Usifungue akaunti kwa mtoto kwa makusudi au kuweka taarifa za watoto zisizohusiana na huduma.', 'Taarifa hii inaweza kubadilishwa kufuata huduma au sheria. Toleo la sasa litaendelea kupatikana. Tutatoa taarifa ya ziada au kuomba ridhaa pale mabadiliko makubwa ya uchakataji yanapohitaji hivyo.'] },
    ] },
  },
};
