// Builds a PDF invoice for every delivered marketplace order and sends it to
// the shop that placed it.
//
// Same shape as generate-invoice: pdf-lib, upload to the private `invoices`
// bucket, no Node polyfills. Driven by pg_cron through net.http_post, so it
// needs no external scheduler and no server of the operator's own.
//
// Money note: nothing here computes a price. unit_price came from the
// supplier's own wholesale price at the moment the order was placed, and the
// total was fixed in marketplace_claim_invoices. This renders what was agreed.
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0';
import { PDFDocument, StandardFonts, rgb } from 'https://esm.sh/pdf-lib@1.17.1';
import { corsHeaders } from '../_shared/cors.ts';
import { sendWhatsAppDocument } from '../_shared/whatsappApi.ts';

type Claim = {
  orderId: string;
  invoiceNo: string;
  productName: string;
  quantity: number;
  unit: string | null;
  unitPrice: number;
  total: number;
  currency: string;
  placedAt: string;
  deliveredAt: string | null;
  buyerCompanyId: string;
  buyerName: string;
  supplierName: string;
  buyerPhone: string | null;
  lang: string;
};

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'content-type': 'application/json' },
  });
}

const money = (n: number) => Math.round(n).toLocaleString('en-US');
const day = (iso: string | null) => (iso ? new Date(iso).toISOString().slice(0, 10) : '—');

async function buildPdf(claim: Claim): Promise<Uint8Array> {
  const sw = claim.lang === 'sw';
  const doc = await PDFDocument.create();
  // A4, the paper a Tanzanian shop actually prints on.
  const page = doc.addPage([595.28, 841.89]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const ink = rgb(0.08, 0.09, 0.13);
  const muted = rgb(0.42, 0.45, 0.5);
  const line = rgb(0.85, 0.87, 0.9);

  let y = 780;
  const text = (s: string, x: number, size: number, f = font, color = ink) => {
    page.drawText(s, { x, y, size, font: f, color });
  };

  text(sw ? 'ANKARA' : 'INVOICE', 50, 24, bold);
  text(claim.invoiceNo, 50, 11, font, muted);
  y -= 18;
  text('Risip', 450, 12, bold);

  y = 720;
  page.drawLine({ start: { x: 50, y }, end: { x: 545, y }, thickness: 1, color: line });

  // Who owes whom. Named plainly: this is the document a trader files.
  y -= 30;
  text(sw ? 'MUUZAJI' : 'SUPPLIER', 50, 9, bold, muted);
  text(sw ? 'MNUNUZI' : 'BUYER', 320, 9, bold, muted);
  y -= 16;
  text(claim.supplierName, 50, 12, bold);
  text(claim.buyerName, 320, 12, bold);

  y -= 34;
  text(sw ? 'Tarehe ya oda' : 'Ordered', 50, 9, bold, muted);
  text(sw ? 'Tarehe ya kufikishwa' : 'Delivered', 320, 9, bold, muted);
  y -= 15;
  text(day(claim.placedAt), 50, 11);
  text(day(claim.deliveredAt), 320, 11);

  y -= 40;
  page.drawRectangle({ x: 50, y: y - 6, width: 495, height: 26, color: rgb(0.96, 0.97, 0.98) });
  text(sw ? 'BIDHAA' : 'ITEM', 60, 9, bold, muted);
  text(sw ? 'IDADI' : 'QTY', 330, 9, bold, muted);
  text(sw ? 'BEI' : 'UNIT', 400, 9, bold, muted);
  text(sw ? 'JUMLA' : 'TOTAL', 480, 9, bold, muted);

  y -= 30;
  text(claim.productName, 60, 11);
  text(`${money(claim.quantity)}${claim.unit ? ` ${claim.unit}` : ''}`, 330, 11);
  text(money(claim.unitPrice), 400, 11);
  text(money(claim.total), 480, 11);

  y -= 22;
  page.drawLine({ start: { x: 50, y }, end: { x: 545, y }, thickness: 1, color: line });

  y -= 26;
  text(sw ? 'JUMLA KUU' : 'TOTAL DUE', 330, 12, bold);
  text(`${claim.currency} ${money(claim.total)}`, 440, 12, bold);

  // Payment is explicitly out of scope: Risip records the trade, the two shops
  // settle it between themselves. Saying so on the document avoids a shop
  // believing Risip took the money.
  y -= 60;
  text(
    sw
      ? 'Malipo hufanyika kati ya maduka yenyewe. Risip haipokei fedha za bidhaa.'
      : 'Payment is settled directly between the two shops. Risip does not collect it.',
    50, 9, font, muted,
  );
  y -= 14;
  text(
    sw ? 'Hati hii imetengenezwa na Risip.' : 'This document was generated by Risip.',
    50, 9, font, muted,
  );

  return await doc.save();
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  const supabaseUrl = Deno.env.get('SUPABASE_URL');
  const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
  if (!supabaseUrl || !serviceKey) return json({ error: 'not_configured' }, 503);

  // Shared secret in a header, the same way ops-watch is called from pg_cron.
  // The service key is deliberately NOT the credential: pg_cron would have to
  // hold it, and a scheduler that can do anything is a scheduler worth
  // stealing. This secret can only run invoices.
  const expected = Deno.env.get('MARKETPLACE_INVOICE_SECRET') ?? '';
  const given = req.headers.get('x-invoice-secret') ?? '';
  if (!expected || given !== expected) return json({ error: 'unauthorized' }, 401);

  const db = createClient(supabaseUrl, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const { data, error } = await db.rpc('marketplace_claim_invoices', { p_limit: 10 });
  if (error) return json({ error: 'claim_failed', code: error.code }, 500);
  const claims = (data ?? []) as Claim[];
  const result = { claimed: claims.length, built: 0, sent: 0, failed: 0 };

  for (const claim of claims) {
    let path: string | null = null;
    let sent = false;
    let failure: string | null = null;
    try {
      const bytes = await buildPdf(claim);
      // First path segment is the order id, so the bucket keeps the shape its
      // storage policies expect (a uuid, then the file).
      path = `${claim.orderId}/invoice.pdf`;
      const up = await db.storage.from('invoices')
        .upload(path, bytes, { contentType: 'application/pdf', upsert: true });
      if (up.error) throw new Error(`upload_failed`);
      result.built += 1;

      if (claim.buyerPhone) {
        // Meta fetches this itself, so an hour is ample and the file stays
        // private afterwards.
        const signed = await db.storage.from('invoices').createSignedUrl(path, 3600);
        if (signed.error || !signed.data?.signedUrl) throw new Error('sign_failed');
        const sw = claim.lang === 'sw';
        const out = await sendWhatsAppDocument(
          claim.buyerPhone,
          signed.data.signedUrl,
          `${claim.invoiceNo}.pdf`,
          sw
            ? `Ankara ${claim.invoiceNo} — ${claim.supplierName}. Jumla ${claim.currency} ${money(claim.total)}.`
            : `Invoice ${claim.invoiceNo} from ${claim.supplierName}. Total ${claim.currency} ${money(claim.total)}.`,
        );
        sent = out.ok;
        if (!out.ok) {
          // 131047 is Meta refusing a message outside the 24h window. It needs
          // an approved template with a document header, not a retry.
          failure = out.code === 131047
            ? 'outside_service_window_template_required'
            : `meta_${out.status ?? 'no_response'}_${out.code ?? 'unknown'}`;
        }
      } else {
        failure = 'buyer_has_no_verified_whatsapp';
      }
    } catch (err) {
      failure = err instanceof Error ? err.message : 'invoice_failed';
    }

    if (sent) result.sent += 1; else result.failed += 1;
    // The PDF is recorded even when the send fails: the buyer can still open it
    // in the app, which needs nobody's approval.
    await db.rpc('marketplace_mark_invoice', {
      p_order_id: claim.orderId, p_path: path, p_sent: sent, p_error: failure,
    });
  }

  return json(result);
});
